### ISSUE TITLE
Test PCBs // Add Contact Data

### ISSUE THREAD

**Issue by basst22778** [turrican944/OpenDTU-PCB#1]
Hi, 
Ich hätte Interesse an PCBs aus Deiner Testbestellung. Wenn du noch welche übrig hasts…

Es gibt aber keine Kontaktdaten in deinem Repo.
 
—
BassT

**Comment by turrican944** [comment]
Moin
Ne sind noch keine Kontaktdaten drin, ich habe es auch noch nicht fertig.
Leiterplatten sind noch nicht da, aber ich habe davon dann auch leider
keine mehr über.

Gruß Florian

basst22778 ***@***.***> schrieb am Mi., 1. März 2023, 21:12:

**Comment by basst22778** [comment]
Alles klar! dann warte ich mal ab ob das Layout bei Dir funktioniert und geb dann selbst ne Bestellung auf.

**Comment by turrican944** [comment]
Moin
Ich gehe schon davon aus daß es funktioniert. Ich habe noch bischen was
geändert. Ein Text war noch versetzt und noch ein paar Masse
Durchkontaktierungen mehr rein, ich warte aber immer noch auf die erste
Charge. Die Änderungen sollte aber wenn die erste funktioniert auch passen.
Aber evtl Order ich nochmal nach weil natürlich alle Kumpels sowas wollen.
Aber es ist ja immer so Zeit ist knapp.

Gruß Florian

basst22778 ***@***.***> schrieb am Mi., 1. März 2023, 23:34:
