### ISSUE TITLE
Kleiner Fehler im opendtu V2.pdf

### ISSUE THREAD

**Issue by swan99de** [turrican944/OpenDTU-PCB#4]
In die Beschriftung für die Polung der Jumper hat sich im opendtu V2.pdf ein kleiner Fehler eingeschlichen.
J1 1-2 1+   J2 2-3 1-
J2 1-2 2-   J2 2-3 2+
Jumper2 ist 3x und Jumper1 nur 1x aufgeführt

Der Aufdruck auf der Platine ist korrekt
J1 1-2 1+
J2 1-2 2-

J1 2-3 1-
J2 2-3 2+

**Comment by turrican944** [comment]
Moin
Guck an ist mir noch garnicht aufgefallen ;-) , ich habe es mal korrigiert, tippfehler kommen halt mal vor.
